name: 'greenhouse_source_integration_tests'
version: '0.1.0'
config-version: 2
profile: 'integration_tests'


vars:
  greenhouse_source:
    activity: "{{ ref('activity') }}" 
    application: "{{ ref('application') }}" 
    application_history: "{{ ref('application_history') }}" 
    attachment: "{{ ref('attachment') }}" 
    candidate: "{{ ref('candidate') }}" 
    candidate_tag: "{{ ref('candidate_tag') }}" 
    department: "{{ ref('department') }}" 
    eeoc: "{{ ref('eeoc') }}" 
    email_address: "{{ ref('email_address') }}" 
    hiring_team: "{{ ref('hiring_team') }}" 
    interview: "{{ ref('interview') }}" 
    job: "{{ ref('job') }}" 
    job_department: "{{ ref('job_department') }}" 
    job_office: "{{ ref('job_office') }}" 
    job_opening: "{{ ref('job_opening') }}" 
    job_post: "{{ ref('job_post') }}" 
    job_stage: "{{ ref('job_stage') }}" 
    job_application: "{{ ref('job_application') }}" 
    office: "{{ ref('office') }}" 
    phone_number: "{{ ref('phone_number') }}" 
    prospect_pool: "{{ ref('prospect_pool') }}" 
    prospect_stage: "{{ ref('prospect_stage') }}" 
    scheduled_interview: "{{ fivetran_utils.snowflake_seed_data('scheduled_interview') }}" 
    scheduled_interviewer: "{{ ref('scheduled_interviewer') }}" 
    scorecard: "{{ ref('scorecard') }}" 
    scorecard_attribute: "{{ ref('scorecard_attribute') }}" 
    social_media_address: "{{ ref('social_media_address') }}" 
    source: "{{ ref('source') }}" 
    tag: "{{ ref('tag') }}" 
    user: "{{ ref('user') }}" 
    user_email: "{{ ref('user_email') }}" 

  greenhouse_application_custom_columns: ['custom_what_is_your_preferred_pronoun_', 'custom_how_did_you_hear_about_fivetran_']
  greenhouse_job_custom_columns: ['custom_employment_type', 'custom_stock_options']
  
  greenhouse_using_eeoc: true
  greenhouse_using_app_history: true
  greenhouse_using_prospects: true

seeds:
  greenhouse_source_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    activity:
      +column_types:
        created_at: timestamp
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        user_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    application:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        applied_at: timestamp
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        credited_to_user_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        current_stage_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        last_activity_at: timestamp
        prospect_owner_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        prospect_pool_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        prospect_stage_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        rejected_reason_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        source_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        rejected_at: timestamp
        is_deleted: boolean
    application_history:
      +column_types:
        updated_at: timestamp
        application_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        new_stage_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    attachment:
      +column_types:
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    candidate:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        coordinator_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        last_activity: timestamp
        new_candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        recruiter_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        updated_at: timestamp
    candidate_tag:
      +column_types:
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        tag_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    department:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        parent_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    eeoc:
      +column_types:
        application_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        disability_status_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        gender_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        race_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        veteran_status_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        submitted_at: timestamp
    email_address: 
      +column_types:
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    hiring_team: 
      +column_types:
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        user_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    interview: 
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_stage_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    job:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        closed_at: timestamp
        created_at: timestamp
        updated_at: timestamp
    job_application:
      +column_types:
        application_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    job_department:
      +column_types:
        department_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    job_office:
      +column_types:
        office_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    job_opening:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        application_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        close_reason_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        closed_at: timestamp
        opened_at: timestamp
    job_post:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        updated_at: timestamp
    job_stage:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        updated_at: timestamp
    office:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        parent_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        primary_contact_user_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    phone_number:
      +column_types:
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"   
        index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}" 
    prospect_pool:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    prospect_stage:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        prospect_pool_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    scheduled_interview:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        application_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        interview_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        organizer_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        end: timestamp
        start: timestamp
        updated_at: timestamp
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"
      +enabled: "{{ true if target.type != 'snowflake' else false }}"
    scheduled_interview_snowflake:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        application_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        interview_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        organizer_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        end: timestamp
        # start: timestamp
        updated_at: timestamp
      +enabled: "{{ true if target.type == 'snowflake' else false }}"
    scheduled_interviewer:
      +column_types:
        interviewer_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        scheduled_interview_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        scorecard_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    scorecard:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        application_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        submitted_by_user_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        interviewed_at: timestamp
        submitted_at: timestamp
        updated_at: timestamp
    scorecard_attribute:
      +column_types:
        index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        scorecard_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    social_media_address:
      +column_types:
        index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    source:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        source_type_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    tag:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    user:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
    user_email:
      +column_types:
        user_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"

